[package]
name = "aw-fm"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT"
keywords = ["gui", "file-manager"]
homepage = "https://github.com/awused/aw-fm"
repository = "https://github.com/awused/aw-fm"
links = "GTK4, X11"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.3"
async-channel = "1.9.0"
awconf = { git = "https://github.com/awused/awconf" }
chrono = "0.4.26"
clap = { version = "4.3.11", features = ["derive"] }
derive_more = { version = "0.99.17", default-features = false, features = ["deref", "deref_mut", "from"] }
dirs = "5.0.1"
env_logger = { version = "0.10.0", default-features = false, features = ["auto-color", "color"] }
futures-util = { version = "0.3.28", default-features = false }
futures-executor = { version = "0.3.28", default-features = false }
gtk = { package = "gtk4", features = ["v4_10"], version = "0.6.6" }
humansize = "2.1.3"
log = "0.4.19"
notify = "6.0.1"
num_cpus = "1.16.0"
once_cell = "1.18.0"
ouroboros = "0.17.0"
path-clean = "1.0.1"
rayon = "1.7.0"
regex = "1.9.1"
rusqlite = { version = "0.29.0", features = ["bundled"] }
serde = { version = "1.0.171", default-features = false, features = ["derive"] }
serde_json = "1.0.100"
strum = "0.25.0"
strum_macros = "0.25"
tempfile = "3.6.0"
tokio = { version = "1.29.1", features = ["fs", "net", "macros", "process", "rt", "sync", "time"] }


# This is auto-generated, but pretty much left unmaintained and abandoned.
# Local patched version to generate what I need and expose the "v42" feature.
gnome-desktop = { path = "../../third_party/gnome-desktop-rs/gnome-desktop", features = [ "v42" ] }


[target.'cfg(unix)'.dependencies]
# gdk4-x11 = "0.5.0"
signal-hook = "0.3.15"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.5.0", features = [ "background_threads" ] }


[package.metadata.pkg-config]
gtk4 = "4.10"

[build-dependencies]
metadeps = "1.1.2"
pkg-config = "0.3.27"

[features]
debug-forced-slow = []
