[package]
name = "aw-fm"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT"
keywords = ["gui", "file-manager"]
homepage = "https://github.com/awused/aw-fm"
repository = "https://github.com/awused/aw-fm"
links = "GTK4, X11"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.3"
async-channel = "1.9.0"
awconf = { git = "https://github.com/awused/awconf" }
chrono = { version = "0.4.26", default-features = false, features = ["clock", "std"] }
clap = { version = "4.3.23", features = ["derive"] }
derive_more = { version = "0.99.17", default-features = false, features = ["deref", "deref_mut", "from"] }
dirs = "5.0.1"
env_logger = { version = "0.10.0", default-features = false, features = ["auto-color", "color"] }
futures-util = { version = "0.3.28", default-features = false }
futures-executor = { version = "0.3.28", default-features = false }
gtk = { version = "0.7.2", package = "gtk4", features = ["gnome_44"]}
humansize = "2.1.3"
ignore = "0.4.20"
libc = "0.2.147"
log = "0.4.20"
notify = "6.1.1"
num_cpus = "1.16.0"
once_cell = "1.18.0"
ouroboros = "0.17.2"
path-clean = "1.0.1"
rayon = "1.7.0"
regex = "1.9.3"
rusqlite = { version = "0.29.0", features = ["bundled"] }
serde = { version = "1.0.185", default-features = false, features = ["derive"] }
strum = "0.25.0"
strum_macros = "0.25"
tokio = { version = "1.32.0", features = ["fs", "net", "macros", "process", "rt", "sync", "time"] }
toml = "0.7.6"

# This is auto-generated, but pretty much left unmaintained and abandoned.
# Local patched version to generate what I need and expose the "v42" feature.
gnome-desktop = { git = "https://github.com/awused/gnome-desktop-rs", features = [ "v42" ] }


[target.'cfg(unix)'.dependencies]
# gdk4-x11 = "0.5.0"
signal-hook = "0.3.17"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.5.4", features = [ "background_threads" ] }


[package.metadata.pkg-config]
gtk4 = "4.10"

[build-dependencies]
metadeps = "1.1.2"
pkg-config = "0.3.27"

[features]
debug-forced-slow = []
